#!/bin/sh
if [ -z "$${IPKG_INSTROOT}" ]; then
	( . /etc/uci-defaults/luci-chinadns ) && rm -f /etc/uci-defaults/luci-chinadns
	chmod 755 /etc/init.d/chinadns >/dev/null 2>&1
	/etc/init.d/chinadns enable >/dev/null 2>&1
fi
exit 0
