#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@amule[-1]
	add ucitrack amule
	set ucitrack.@amule[-1].init=amule
	commit ucitrack
EOF

while [ ! $(grep -e "amule" /etc/passwd) ]
do 
    gid=$(awk -v min=1000 -v max=1500 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
    echo amule:x:0:0:99999:7::: >> /etc/shadow
    grep -e ":$gid:" /etc/passwd || ( \
	echo "amule:x:$gid:amule" >> /etc/group ; \
	echo "amule:x:$gid:$gid:amule:/var/run/amule:/bin/false" >> /etc/passwd )
    sleep 1
done

mkdir -p /etc/amule/
touch /etc/amule/addresses.dat
touch /etc/amule/ipfilter_static.dat
touch /etc/amule/shareddir.dat

rm -f /tmp/luci-indexcache
exit 0
